/******************************************************************************/
/* This file has been generated by the uGFX-Studio                            */
/*                                                                            */
/* http://ugfx.org                                                            */
/******************************************************************************/

#include "colors.h"
#include "widgetstyles.h"
#include "gui.h"
#include "math.h"
#include "stdio.h"
#include "stdlib.h"

#define PRINTER(name) (#name)

#define SCREEN_WIDTH GDISP_SCREEN_WIDTH
#define SCREEN_HEIGHT GDISP_SCREEN_HEIGHT

// GListeners
GListener glistener;

// GHandles
GHandle ghContainerMenu;
GHandle ghContainerSettings;

// Fonts
font_t dejavu_sans_16;
// Images
gdispImage _leer;
gdispImage _obenlinks;
gdispImage _obenmitte;
gdispImage _obenrechts;
gdispImage _untenlinks;
gdispImage _untenmitte;
gdispImage _untenrechts;
gdispImage einstellungen;
gdispImage schliessen;
gdispImage zurueck;

//If a functionless button was pressed, do nothing
void nothing(GHandle gh) {
	(void) gh;
}
//If a suicidal button was pressed, destroy it
void destroy(GHandle gh) {
	gwinDestroy(gh);
}

//If the main menu button was pressed, show the main menu page
void showMainMenu(GHandle gh) {
	(void) gh;
	gwinHide(ghContainerSettings);
	gwinDestroy(ghContainerSettings);
	createMenu();
	gwinShow(ghContainerMenu);
}

//If the settings button was pressed, show the settings page
void showSettings(GHandle gh) {
	(void) gh;
	gwinHide(ghContainerMenu);
	gwinDestroy(ghContainerMenu);
	createSettings();
	gwinShow(ghContainerSettings);
}

//If the close button was pressed, close the window
void closeWindow(GHandle gh) {
	(void) gh;
	exit(0);
}

//Define the dimensions used for each button (x coordinate, y coordinate, width, height) (by index)
double buttonDimensions[6][4] = {
	{0,						0,					SCREEN_WIDTH / 3,	SCREEN_HEIGHT / 2},
	{SCREEN_WIDTH / 3,		0,					SCREEN_WIDTH / 3,	SCREEN_HEIGHT / 2},
	{SCREEN_WIDTH / 3 * 2,	0,					SCREEN_WIDTH / 3,	SCREEN_HEIGHT / 2},
	{0,						SCREEN_HEIGHT / 2,	SCREEN_WIDTH / 3,	SCREEN_HEIGHT / 2},
	{SCREEN_WIDTH / 3,		SCREEN_HEIGHT / 2,	SCREEN_WIDTH / 3,	SCREEN_HEIGHT / 2},
	{SCREEN_WIDTH / 3 * 2,	SCREEN_HEIGHT / 2,	SCREEN_WIDTH / 3,	SCREEN_HEIGHT / 2}
};

//Define the labels used for each button (by index)
char *buttonLabels[6];

//Define the images used for each button (by index)
gdispImage *buttonImages[6];

//Define the functions called for each button (by index)
void (*buttonFunctions[6])(GHandle gh);

//Create a generic button with custom dimensions, label, image and tag
void createButton(GWidgetInit wi, int index, GHandle parent) {
	wi.g.show = TRUE;
	wi.g.x = ceil(buttonDimensions[index][0]);
	wi.g.y = ceil(buttonDimensions[index][1]);
	wi.g.width = ceil(buttonDimensions[index][2]);
	wi.g.height = ceil(buttonDimensions[index][3]);
	wi.g.parent = parent;
	wi.text = buttonLabels[index];
	wi.customDraw = gwinButtonDraw_Image;
	wi.customParam = buttonImages[index];
	wi.customStyle = 0;
	wi.tag = index;
	/*ghButton1 =*/ gwinButtonCreate(0, &wi);
}

//Create main menu page
void createMenu(void) {
	GWidgetInit wi;
	gwinWidgetClearInit(&wi);

	// create container widget
	wi.g.show = FALSE;
	wi.g.x = 0;
	wi.g.y = 0;
	wi.g.width = SCREEN_WIDTH;
	wi.g.height = SCREEN_HEIGHT;
	wi.g.parent = 0;
	wi.text = "Container";
	wi.customDraw = 0;
	wi.customParam = 0;
	wi.customStyle = 0;
	ghContainerMenu = gwinContainerCreate(0, &wi, 0);
	
	//page configuration (3x2, indexes from left to right, top to bottom):
	
	//labels (as strings)
	buttonLabels[0] = "Rainwater Filtration";
	buttonLabels[1] = "Infiltration";
	buttonLabels[2] = "";
	buttonLabels[3] = "Greywater Treatment";
	buttonLabels[4] = "Fire Protection Tank";
	buttonLabels[5] = "";
	
	//images (must be defined through guiCreate below)
	buttonImages[0] = &_obenlinks;
	buttonImages[1] = &_obenmitte;
	buttonImages[2] = &einstellungen;
	buttonImages[3] = &_untenlinks;
	buttonImages[4] = &_untenmitte;
	buttonImages[5] = &schliessen;
	
	//functions (must be defined above)
	buttonFunctions[0] = nothing;
	buttonFunctions[1] = nothing;
	buttonFunctions[2] = showSettings;
	buttonFunctions[3] = nothing;
	buttonFunctions[4] = nothing;
	buttonFunctions[5] = closeWindow;
	
	int i;
	for(i = 0; i < 6; i++) {
		createButton(wi, i, ghContainerMenu);
	}
}

//Create settings menu page
void createSettings(void) {
	GWidgetInit wi;
	gwinWidgetClearInit(&wi);

	// create container widget
	wi.g.show = FALSE;
	wi.g.x = 0;
	wi.g.y = 0;
	wi.g.width = SCREEN_WIDTH;
	wi.g.height = SCREEN_HEIGHT;
	wi.g.parent = 0;
	wi.text = "Container";
	wi.customDraw = 0;
	wi.customParam = 0;
	wi.customStyle = 0;
	ghContainerSettings = gwinContainerCreate(0, &wi, 0);
	
	//page configuration (3x2, indexes from left to right, top to bottom):
	
	//labels
	buttonLabels[0] = "Fischers";
	buttonLabels[1] = "Fritz";
	buttonLabels[2] = "fischt";
	buttonLabels[3] = "frische";
	buttonLabels[4] = "Fische";
	buttonLabels[5] = "";
	
	//images (must be defined under Images above and declared through guiCreate below)
	buttonImages[0] = &_obenlinks;
	buttonImages[1] = &_obenmitte;
	buttonImages[2] = &einstellungen;
	buttonImages[3] = &_untenlinks;
	buttonImages[4] = &_leer;
	buttonImages[5] = &zurueck;
	
	//functions (must be declared above)
	buttonFunctions[0] = nothing;
	buttonFunctions[1] = nothing;
	buttonFunctions[2] = destroy;
	buttonFunctions[3] = nothing;
	buttonFunctions[4] = nothing;
	buttonFunctions[5] = showMainMenu;
	
	int i;
	for(i = 0; i < 6; i++) {
		createButton(wi, i, ghContainerSettings);
	}
}

void guiShowPage(unsigned pageIndex) {
	// Hide all pages
	gwinHide(ghContainerMenu);

	// Show page selected page
	switch (pageIndex) {
	case 0:
		gwinShow(ghContainerMenu);
		break;

	default:
		break;
	}
}

void guiCreate(void) {
	GWidgetInit wi;

	// Prepare fonts
	dejavu_sans_16 = gdispOpenFont("DejaVuSans16");

	geventListenerInit(&glistener);
	gwinAttachListener(&glistener);

	// Prepare images
#if 1
	gdispImageOpenFile(&_leer, "rsc/_leer.gif");
	gdispImageOpenFile(&_obenlinks, "rsc/_obenlinks.gif");
	gdispImageOpenFile(&_obenmitte, "rsc/_obenmitte.gif");
	gdispImageOpenFile(&_obenrechts, "rsc/_obenrechts.gif");
	gdispImageOpenFile(&_untenlinks, "rsc/_untenlinks.gif");
	gdispImageOpenFile(&_untenmitte, "rsc/_untenmitte.gif");
	gdispImageOpenFile(&_untenrechts, "rsc/_untenrechts.gif");
	gdispImageOpenFile(&einstellungen, "rsc/einstellungen.gif");
	gdispImageOpenFile(&schliessen, "rsc/schliessen.gif");
	gdispImageOpenFile(&zurueck, "rsc/zurueck.gif");
#else
	gdispImageOpenFile(&_leer, "rsc/_leer.gif");
	gdispImageOpenFile(&_obenlinks, "rsc/_leer.gif");
	gdispImageOpenFile(&_obenmitte, "rsc/_leer.gif");
	gdispImageOpenFile(&_obenrechts, "rsc/_leer.gif");
	gdispImageOpenFile(&_untenlinks, "rsc/_leer.gif");
	gdispImageOpenFile(&_untenmitte, "rsc/_leer.gif");
	gdispImageOpenFile(&_untenrechts, "rsc/_leer.gif");
	gdispImageOpenFile(&einstellungen, "rsc/_leer.gif");
	gdispImageOpenFile(&schliessen, "rsc/_leer.gif");
	gdispImageOpenFile(&zurueck, "rsc/_leer.gif");
#endif

	// GWIN settings
	gwinWidgetClearInit(&wi);
	gwinSetDefaultFont(dejavu_sans_16);
	gwinSetDefaultStyle(&white, FALSE);
	gwinSetDefaultColor(black_studio);
	gwinSetDefaultBgColor(white_studio);

	// Create all the display pages
	createMenu();
	gwinShow(ghContainerMenu);

	// Select the default display page
	//guiShowPage(0);
}

void guiEventLoop(void) {
	GEvent* pe;

	while (1) {
		// Get an event
		pe = geventEventWait(&glistener, TIME_INFINITE);

		switch (pe->type) {
			case GEVENT_GWIN_BUTTON:
				(*buttonFunctions[((GEventGWinButton*) pe)->tag]) (((GEventGWinButton*) pe)->gwin);
				break;
		
			default:
				break;
		}

	}

}

