/******************************************************************************/
/* This file has been generated by the uGFX-Studio                            */
/*                                                                            */
/* http://ugfx.org                                                            */
/******************************************************************************/

#ifndef _GUI_H_
#define _GUI_H_

#include "gfx.h"


/* Globally used fonts */
extern font_t ctrld_16b;
extern font_t neep_12x24b;
extern font_t term_12b;

//extern font_t fixed_7x14;


// Function Prototypes
void guiCreate(void);

void guiEventLoop(void);


#endif /* _GUI_H_ */
