/******************************************************************************/
/* This file has been generated by the uGFX-Studio                            */
/*                                                                            */
/* http://ugfx.org                                                            */
/******************************************************************************/

#ifndef _TEST_H_
#define _TEST_H_

#include "gfx.h"

//extern font_t dejavu_sans_10;
//extern font_t dejavu_sans_16;


void guiCreate(void);

void guiEventLoop(void);

#endif /* _TEST_H_ */
