/******************************************************************************/
/* This file has been generated by the uGFX-Studio                            */
/*                                                                            */
/* http://ugfx.org                                                            */
/******************************************************************************/

#ifndef _GUI_H_
#define _GUI_H_

#include "gfx.h"

extern font_t dejavu_sans_10;
extern font_t dejavu_sans_16;

extern gdispImage ic_home;
extern gdispImage ic_settings;
extern gdispImage ic_forward;
extern gdispImage ic_local_drink;
extern gdispImage ic_alarm;
extern gdispImage ic_public;
extern gdispImage ic_thumbs_up_down;
extern gdispImage ic_search;
extern gdispImage ic_live_help;

// Function Prototypes
void guiCreate(void);

//void guiShowPage(unsigned pageIndex);
void guiEventLoop(void);

#endif /* _GUI_H_ */
